### ISSUE TITLE
Cannot add new shipping addresses or edit existing shipping addresses

### ISSUE THREAD

**Issue by mwukfr** [crosspeaksoftware/woo-address-book#140]
For some reason my customers can't add new shipping addresses or edit existing ones anymore.
Adding/editing billing addresses works fine, but adding/editing shipping addresses doesn't.
I'm working on v2.3.0 of WooCommerce Address Book, v6.1.1 of Wordpress and v7.1.1 of WooCommerce.

**Comment by matt-h** [comment]
Adding and editing shipping addresses works fine using these versions of WordPress and the plugins.

We would need more details of the issue to try and assist.

**Comment by matt-h** [comment]
Since we have not heard back, we are closing this. If you have more information in the future on how to reproduce your issue feel free to leave a comment.
