### ISSUE TITLE
custom fields

### ISSUE THREAD

**Issue by Fogghy360** [crosspeaksoftware/woo-address-book#141]
Custom fields in the checkout field these are not imported for the various billing addresses, such as the VAT number etc, Or if they are saved it just keeps the last one and overwrites all the others.., it would be very useful if it captured all the fields, especially for companies who maybe have sales agents and need to save multiple billing addresses in their account when placing orders for customers (like in my case) otherwise, each time they have to write the VAT number data and any other data (depending on the state) by hand each time.

**Comment by matt-h** [comment]
This plugin uses the Address fields from WooCommerce as it defines them. These are the fields that WooCommerce considers part of the Address from the Edit Address pages. They should all work correctly if they are either Billing or Shipping address fields however this does not include additional checkout fields or address modifications made for the checkout but not the address fields..

If you don't have this plugin active and you go to edit the Billing or Shipping address in My Account the fields that you see there are the fields that are tied to the address.

Typically fields that are supported are fields that are added with the `woocommerce_billing_fields` or `woocommerce_shipping_fields` filters in WooCommerce. This does not include the customization with the filter `woocommerce_checkout_fields` as that does not affect the WooCommerce address.

So, if you include your VAT number field on either the Billing or Shipping address it will be captured along with the address.

**Comment by matt-h** [comment]
We are closing this issue as there are currently no items to action on. If you have any more information to add please feel free to leave a comment.
