### ISSUE TITLE
Shipping address > add new

### ISSUE THREAD

**Issue by Data-Zombie** [crosspeaksoftware/woo-address-book#143]
Just one question:

I would like to remove add new from shipping options.

I have tried with css
label[for="shipping_address_book"] span.optional{
	display: none!important;
}

It doesn't work on Safary because Safary CSS restrictions.

There is any function that I can use?

Thanks

**Comment by matt-h** [comment]
This custom function should remove it from the checkout.
```php
function custom_remove_add_new_address_option( $fields ) {
	foreach ( $fields as $type => $address_fields ) {
		if ( isset( $fields[ $type ][ $type . '_address_book' ]['options']['add_new'] ) ) {
			unset( $fields[ $type ][ $type . '_address_book' ]['options']['add_new'] );
		}
	}
	return $fields;
}
add_filter( 'woocommerce_checkout_fields', 'custom_remove_add_new_address_option', 10000, 1 );
```

Alternatively you could set the Address limit in the settings to 1 address which would prevent adding more but any you've already added will show up.

**Comment by Data-Zombie** [comment]
Thanks that's works
