### ISSUE TITLE
Update shipping field based on the chosen select address

### ISSUE THREAD

**Issue by Data-Zombie** [crosspeaksoftware/woo-address-book#144]
Hello Mat,
just doing a few test on it.

I have injected this code into child theme function.php

add_action( 'wp_enqueue_scripts', 'custom_address_book_scripts', 20 );
function custom_address_book_scripts() {
wp_enqueue_script( 'woo-address-book' );
}

It works for the first items added to the cart but if I remove the items and then add again other fields are not active.
I have a video to show better the case.
What do you think?

https://user-images.githubusercontent.com/121128791/210260237-c3fab1b7-a5fa-4a5f-888a-b9b3fb7c6638.mp4

**Comment by matt-h** [comment]
Looks like it must unload the address form and then reload it so the script loses track of it. It probably would require finding if that cart plugin has a hook in it to trigger when it reloads. Then executing the address book scripts again.

Where that checkout plugin is a paid plugin that I have no knowledge of how it works you might be better of seeing if they can support the Address Book plugin.
The Address Book plugin is pretty simple and hooks into the core WooCommerce checkout fields to make its changes. If there are any hooks that need to be added to this plugin in order for them to support it, just let us know.

**Comment by Data-Zombie** [comment]
Hi Matt,

this is the answer...

They write the JS action on element [https://www.screencast.com/t/UuIL0TD1Qvk5](http://email.ticksymail.com/c/eJwdjc0KAiEURp9mXA56veq4cBFEELQJ6gFu6jDS_DFaQ2-fBefbnMV3ohPagOUaJbLgHqJXwJIDDpILrngnpMK2x6B7bsgEE2KPukFekn_mz0RpbP0yscFRCEBIHsja6CmitNSh11oDoICOjW4oZc2NPDRwquz73ma_xTh7yuX3UmWpu7_OF347iuv7qdjm1i1NC4001-qwlH8ylS_zrTfL), so it doesn't work if the content was loaded/refreshed by AJAX.

If I change the code from:

$( '#billing_address_book_field #billing_address_book' ).on( 'change', function () {
to:

$( document ).on( 'change', '#billing_address_book_field #billing_address_book', function () {
It will work fine on the Fly Cart [https://www.screencast.com/t/TRuzyOGI](http://email.ticksymail.com/c/eJwdjTkOwyAUBU9jSusDHzAFRRpHqSJFuQBmkVG8yRBZzulDIs1rpngTDJWKaZDIkXgz0CgYSYYB40BBQEe5wDailxGUVV75EFE2CCW5Vz5nm6bWrTMZDXOOW_SguQPQArUUoHEYNPVdZ6kikxlL2XLDLw3rK8dxtNntISzO5vJ7qbLUPR_vz3m_3shutj3Nq53sUovjWv65VL7Z7TY-) (screen record video).

**Comment by Data-Zombie** [comment]
Same things for shipping fields.
It solve my case.
Thanks Matt.
Can I buy you a coffee for the assistance?
Send me the link. Thanks

**Comment by matt-h** [comment]
This has now been updated in version 2.4.1 with the changes so it will still listen for the actions even when the checkout refreshes.


If you would like, feel free to see our premium plugins at https://www.crosspeaksoftware.com/ (more will be coming soon)
Or we can process payments here: https://www.crosspeaksoftware.com/process-payment/
