### ISSUE TITLE
Instead of nick name it showing {address_nickname} on my account address book 

### ISSUE THREAD

**Issue by Dextra555** [crosspeaksoftware/woo-address-book#149]
Instead of nickname it shows {address_nickname} on my account address book.
kindly check these links I added a nickname as work but not showing in woo address book 
https://tinyurl.com/2gf9n2hx
https://tinyurl.com/2loautlb

**Comment by matt-h** [comment]
Hi,

We have looked into this and we have not been able to reproduce the issue.

The only thing I can think of so far is if you have a plugin that doesn't properly use the `woocommerce_formatted_address_replacements` filter and overrides the replacements that we set for this field.

**Comment by matt-h** [comment]
Closing this out since we haven't heard back. If you have any further information, feel free to add it here.
