### ISSUE TITLE
Hook: There is any hook I can use for remove nickname from the select dropdown?

### ISSUE THREAD

**Issue by Data-Zombie** [crosspeaksoftware/woo-address-book#151]
Hello Matt,

I have one question: In my case Nickname and Name are the same.
Is possible to remove from the select the address nickname?
Now it looks like 1001640: 101640 ....
I would like appear like this 1001640....

Thank

<img width="592" alt="Schermata 2023-09-22 alle 01 09 20" src="https://github.com/crosspeaksoftware/woo-address-book/assets/121128791/2905bd3e-6e24-40df-bb5e-53c8ece9c98b">

**Comment by matt-h** [comment]
Nickname is an optional field, so could you just leave that blank in those cases?

If you need to remove it in code somehow, there is a filter on `wc_address_book_address_select_label` where you could customize the label for each address as it generates them.

**Comment by Data-Zombie** [comment]
Thanks for the answer. I thought Nickname was mandatory.
