### ISSUE TITLE
Disable 'Add New Address' Option

### ISSUE THREAD

**Issue by BenSGA** [crosspeaksoftware/woo-address-book#156]
Hello,

I'm wondering if it's possible to deactivate the 'Add New Address' option during checkout, so users are required to choose from a pre-set list of addresses. I've configured an internal store using WooCommerce, where I've listed various addresses for managers across my company and it would be great if they could only select from these pre-set addresses.

Thanks!

**Comment by matt-h** [comment]
You can use this code snippet for removing the add new address options from checkout.

```php
function remove_add_new_address( $fields ) {
	if ( isset( $fields['billing']['billing_address_book']['options']['add_new'] ) ) {
		unset( $fields['billing']['billing_address_book']['options']['add_new'] );
	}
	if ( isset( $fields['shipping']['shipping_address_book']['options']['add_new'] ) ) {
		unset( $fields['shipping']['shipping_address_book']['options']['add_new'] );
	}

	return $fields;
}
add_filter( 'woocommerce_checkout_fields', 'remove_add_new_address', 20000, 1 );
```
