### ISSUE TITLE
User Profile Updates Issue in v3.x

### ISSUE THREAD

**Issue by dashkevych** [crosspeaksoftware/woo-address-book#158]
Hello CrossPeak team,

First of all, thank you for this plugin. There are many plugins that offer similar functionality but the ones that I have tried do not have such a good code quality (and simplicity) as your plugin.

I've seen [your blog post](https://www.crosspeaksoftware.com/blog/woo-address-book-version-3-0-0-release/) about release of v3 of the WooCommerce Address Book plugin, and the reason why [v3 is not currently available at WordPress.org](https://wordpress.org/support/topic/v3-ready/) by default.

I've tested both versions ([v3.0.2](https://plugins.trac.wordpress.org/browser/woo-address-book/tags/3.0.2) and [v2.6.3](https://plugins.trac.wordpress.org/browser/woo-address-book/tags/2.6.3)) on my local environments and I found a (breaking) issue in v3.0.2.
Note, I have tested these two versions on a clean WordPress installation with only WooCommerce and WooCommerce Address Book plugins active.

Let's say I have the following addresses saved on my website:

**Billing Address (Default):**
_Tom Doe
131 W 55th St, 
New York, NY 10019
United States_

**Shipping Address (Default):**
_Tom Doe
131 W 55th St, 
New York, NY 10019
United States_

**Shipping Address (Additional):**
_Kate Smith
Bruno-Kreisky-Platz 1, 
Vienna 1220 
Austria_

**Steps to Reproduce**
1. Add product to cart;
2. Go to checkout (the checkout page is built using a WooCommerce shortcode);
3. Check "Ship to a different address";
4. Select not default shipping address from Address Book;
5. Make a purchase;

After that, visit your profile page at `wp-admin/profile.php`.

**Current Behavior in v3.0.2**

On your profile page, notice changes in the following section:

- Name (First and Last names are changed based on data from Additional Shipping Address);
- Customer billing address (City, Zip, Country fields are changed based on data from Additional Shipping Address)
- Customer shipping address (fields are changed based on data from Additional Shipping Address)

Also, when you go back to `/my-account/edit-addresses/`, the following php error is show: `Fatal error: Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, array given...`

**Current Behavior in v2.6.3**

No changes on your profile page.

**Expected Behavior**

I expect that v3.0.2 should act the same as v2.6.3 in terms of keeping profile data unchanged.

**Comment by matt-h** [comment]
Thank you for the report. It looks like you have tested the [3.0.2](https://plugins.trac.wordpress.org/browser/woo-address-book/tags/3.0.2) version from wordpress.org

We have since done a lot of work to improve the plugin for a new 3.1 launch since the failed launch of 3.0 making it even better then before. The code here on the `main` branch on github is the latest update of that. (I just pushed the last bit of updates we had as well).

Could you test this version of the plugin instead and let us know if you are still having the same issue?

**Comment by dashkevych** [comment]
I have tested the latest version (from Github) and it works as expected, without the user profile issues.
Thank you.
